apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: jayparmar98/laravel-10-curd:0.6  # ✅ Correct image name
          imagePullPolicy: IfNotPresent
          args:
            - jayparmar98/laravel-10-curd:latest
          env:
            - name: APP_ENV
              value: "development"
          ports:
            - containerPort: 9000  # ✅ php-fpm listens on port 9000 by default
          workingDir: /var/www
          volumeMounts:
            - name: app-volume
              mountPath: /var/www
      volumes:
        - name: app-volume
          hostPath:
            path: /absolute/path/to/your/codebase  # 🔧 Replace with real path on host
            type: DirectoryOrCreate
